services:
  sge.postgres:
    image: postgres:latest # Utilise la dernière version de l'image officielle PostgreSQL
    container_name: sge_postgres
    environment:
      POSTGRES_DB: sgedb
      POSTGRES_USER: sgeuser
      POSTGRES_PASSWORD: sgepassword
    ports:
      - "5432:5432" # Exposer le port pour accès depuis l'hôte (optionnel en dev)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistance des données
    networks:
      - sge_network

  sge.api:
    image: sge.api
    build:
      context: . # Contexte de build (racine solution)
      dockerfile: SGE.API/Dockerfile # Chemin vers le Dockerfile du projet API
    container_name: sge_api
    ports:
      - "5000:80" # Mappe le port 80 du conteneur sur 5000 de l'hôte
    depends_on:
      - sge.postgres # Démarre Postgres avant l'API (ordre, pas garantie de readiness)
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=sge.postgres;Database=sgedb;Username=sgeuser;Password=sgepassword"
    networks:
      - sge_network

volumes:
  postgres_data: # Volume pour persister la BDD (sinon perte des données au redémarrage)

networks:
  sge_network:
    driver: bridge
